#!/bin/bash
LANG=cs_CZ.UTF-8
#TODO hlavička souboru
#TODO err zprávy na stderr
#!BUG bez filtru to počítá i první řádek infected

########################### FUNKCE #################################
## Help ##
print_help () {
    echo -e '\e[1;mJMÉNO\033[0m'
    echo -e '  \033[1mcorona\033[0m — analyzátor záznamů osob s prokázanou nákazou koronavirem\n   způsobujícím onemocnění COVID-19\n'

    echo -e '\033[1mPOUŽITÍ\033[0m'
    echo -e '  \033[1mcorona\033[0m [\033[4m-h\033[0m] [\033[4mFILTERS\033[0m] [\033[4mCOMMAND\033[0m] [\033[4mLOG\033[0m [\033[4mLOG2\033[0m [...]]\n'

    echo -e '\033[1mVOLBY\033[0m'
    echo -e '  \033[1mCOMMAND\033[0m může být jeden z:'
    echo -e '      \033[1minfected\033[0m — spočítá počet nakažených.'
    echo -e '      \033[1mmerge\033[0m — sloučí několik souborů se záznamy do jednoho, zachovávající původní pořadí (hlavička bude ve výstupu jen jednou).'
    echo -e '      \033[1mgender — vypíše počet nakažených pro jednotlivá pohlaví.'
    echo -e '      \033[1mage\033[0m — vypíše statistiku počtu nakažených osob dle věku (bližší popis je níže).'
    echo -e '      \033[1mdaily\033[0m — vypíše statistiku nakažených osob pro jednotlivé dny.'
    echo -e '      \033[1mmonthly\033[0m — vypíše statistiku nakažených osob pro jednotlivé měsíce.'
    echo -e '      \033[1myearly\033[0m — vypíše statistiku nakažených osob pro jednotlivé roky.'
    echo -e '      \033[1mcountries\033[0m — vypíše statistiku nakažených osob pro jednotlivé země nákazy (bez ČR, tj. kódu CZ).'
    echo -e '      \033[1mdistricts\033[0m — vypíše statistiku nakažených osob pro jednotlivé okresy.'
    echo -e '      \033[1mregions\033[0m — vypíše statistiku nakažených osob pro jednotlivé kraje.'
    echo ''
   
    
    echo -e '  \033[1mFILTERS\033[0m může být kombinace následujících (každý maximálně jednou):'
    echo -e '      \033[1m-a DATETIME\033[0m — after: jsou uvažovány pouze záznamy PO tomto datu (včetně tohoto data). DATETIME je formátu YYYY-MM-DD.'
    echo -e '      \033[1m-b DATETIME\033[0m — before: jsou uvažovány pouze záznamy PŘED tímto datem (včetně tohoto data).'
    echo -e '      \033[1m-g GENDER\033[0m — jsou uvažovány pouze záznamy nakažených osob daného pohlaví. GENDER může být M (muži) nebo Z (ženy).'
    echo -e '      \033[1m-s [\033[4mWIDTH]\033[0m u příkazů gender, age, daily, monthly, yearly, countries, districts a regions vypisuje data ne číselně, ale graficky v podobě histogramů. Nepovinný parametr WIDTH nastavuje šířku histogramů, tedy délku nejdelšího řádku, na WIDTH. Tedy, WIDTH musí být kladné celé číslo. Pokud není parametr WIDTH uveden, řídí se šířky řádků výchozími hodnotami.'
    echo -e '      \033[1m-d DISTRICT_FILE\033[0m — pro příkaz districts vypisuje místo LAU 1 kódu okresu jeho jméno. Mapování kódů na jména je v souboru DISTRICT_FILE --neimlplementováno'   #!--neimlplementováno
    echo -e '      \033[1m-r REGIONS_FILE\033[0m — pro příkaz regions vypisuje místo NUTS 3 kódu kraje jeho jméno. Mapování kódů na jména je v souboru REGIONS_FILE --neimlplementováno'       #!--neimlplementováno

}
hlavicka () {
    echo 'id,datum,vek,pohlavi,kraj_nuts_kod,okres_lau_kod,nakaza_v_zahranici,nakaza_zeme_csu_kod,reportovano_khs'
}
filtr_pohlavi () {
    awk -F, "-vG=$pohlavi" '{
        if (G == "") {print $0} 
        else {
            if ($4 == G)  {print $0}
        } 
    }'
}
filtr_po () {
    awk -F, "-vdatum=$po_datum" '{
        if (datum == "") {
            print $0;
        } else if ($2 >= datum)  {
            print $0;
        } else if ($2 == "") {
            print $0;
        }
    }'
}
filtr_pred () {
    awk -F, "-vdatum=$pred_datum" '{
        if (datum == "") {
            print $0;
        } else if ($2 <= datum)  {
            print $0;
        } else if ($2 == "") {
            print $0;
        } 
    }'
}
filtry () {
    filtr_pohlavi | filtr_pred | filtr_po
}
valid_datum () {
   if [[ -n "$1" ]]; then
        if [[ $1 =~ ^[0-9]{4}-[0-1]{1}[0-9]{1}-[0-3]{1}[0-9]{1}$ ]] && date "+%Y-%m-%d" -d "$1" > /dev/null 2> /dev/null ; then
            return 0
        else
            return 1
        fi 
   fi
}
vek () {
    cat ${soubor}| sed 1d | filtry | awk -F, "-vdelka_grafu=$delka_grafu" 'BEGIN{
        for (i=0; i <= 12; i++) {
            age_count[i]=0;
        }
        age_text[0]="0-5   : ";
        age_text[1]="6-15  : "; 
        age_text[2]="16-25 : "; 
        age_text[3]="26-35 : "; 
        age_text[4]="36-45 : "; 
        age_text[5]="46-55 : "; 
        age_text[6]="56-65 : "; 
        age_text[7]="66-75 : "; 
        age_text[8]="76-85 : "; 
        age_text[9]="86-95 : "; 
        age_text[10]="96-105: "; 
        age_text[11]=">105  : ";
        age_text[12]="None  : ";  
    }
    {
        if ($3 == "") age_count[12]++;
        else if ($3 <= 5) age_count[0]++;
        else if ($3 <= 15) age_count[1]++;
        else if ($3 <= 25) age_count[2]++;
        else if ($3 <= 35) age_count[3]++;
        else if ($3 <= 45) age_count[4]++;
        else if ($3 <= 55) age_count[5]++;
        else if ($3 <= 65) age_count[6]++;
        else if ($3 <= 75) age_count[7]++;
        else if ($3 <= 85) age_count[8]++;
        else if ($3 <= 95) age_count[9]++;
        else if ($3 <= 105) age_count[10]++;
        else if ($3 > 105) age_count[11]++;
        else;
    }
    END{if (delka_grafu == -1) { 
            for (i=0; i < 12; i++) {
                print age_text[i] age_count[i];
            }
            if (age_count[12] > 0) {
                print age_text[12] age_count[12];
            }
        } else {
            if (delka_grafu == 0) {delka_grafu=10000;}
            else {
                tpm=age_count[0];
                for (i=0; i <= 12; i++) {
                    if (tmp < age_count[i] ) {
                        tmp=age_count[i];
                    }
                }
                delka_grafu=int(tmp/delka_grafu);
            }
            for (i=0; i < 12; i++) {
                histogram=sprintf("%"int(age_count[i]/delka_grafu)"s","");  
                gsub(" ","#",histogram); 
                print age_text[i] histogram;
            }
            if (age_count[12] > 0) {
                histogram=sprintf("%"int(age_count[12]/delka_grafu)"s","");  
                gsub(" ","#",histogram); 
                print age_text[i] histogram;
            }
        }    
    }'
}

zeme_nakazy () {
    cat ${soubor}| sed 1d | filtry | sort -t, -k8 | awk -F, "-vdelka_grafu=$delka_grafu" 'BEGIN {
        zeme="";
        count=1;
        pos=0;
        zem_arr[0]=0;
        count_arr[0]=0;
    } 
    {
        if (zeme == "") {
            zeme=$8;
            next;
        }
        if (zeme == $8) {
            count++;
        }
        else {
            if (zeme != "CZ") {
                if (delka_grafu == -1) {
                    print ""zeme": "count"";
                } else if (delka_grafu == 0) {
                    histogram=sprintf("%"int(count/100)"s","");  
                    gsub(" ","#",histogram); 
                    print zeme ": " histogram;
                } else {
                    zem_arr[pos]=zeme;
                    count_arr[pos]=count;
                    pos++;
                }
            }
            count=1;
            zeme=$8;
        }
    }
    END{
        if (delka_grafu == -1) {
            if (zeme != "") {print ""zeme": "count"";}
        } else if (delka_grafu == 0) {
            if (zeme != "") {
                histogram=sprintf("%"int(count/100)"s","");
                gsub(" ","#",histogram); 
                print zeme ": " histogram;
            }
        } else {
            zem_arr[pos]=zeme;
            count_arr[pos]=count;
            tmp=count_arr[0];
            for (i=0; i <= pos; i++) {
                if (tmp < count_arr[i]) {
                    tmp=count_arr[i];
                }
            }
            delka_grafu=int(tmp/delka_grafu);
            for (i=0; i <= pos; i++) {
                histogram=sprintf("%"int(count_arr[i]/delka_grafu)"s","");  
                gsub(" ","#",histogram); 
                print zem_arr[i]": "histogram;
            }
            if (zeme_arr[pos] != "") {
                histogram=sprintf("%"int(count_arr[pos]/delka_grafu)"s","");  
                gsub(" ","#",histogram); 
                print zem_arr[pos]": "histogram;
            }
        }
    }'
}

kraje_nakazy () {
    cat ${soubor}| sed 1d | filtry | sort -t, -k6 | awk -F, "-vdelka_grafu=$delka_grafu" 'BEGIN {
        zeme="";
        count=1;
        none=0;
        pos=0;
        zem_arr[0]=0;
        count_arr[0]=0;
    }
    {
        if ($6 == "") {
            none++;
        } 
    } 
    {
        if (zeme == "") {
            zeme=$6;
            next;
        }
        if (zeme == $6) {
            count++;
        }
        else {
            if (delka_grafu == -1) {
                print ""zeme": "count"";
            } else if (delka_grafu == 0) {
                histogram=sprintf("%"int(count/1000)"s","");  
                gsub(" ","#",histogram); 
                print zeme ": " histogram;
            } else {
                zem_arr[pos]=zeme;
                count_arr[pos]=count;
                pos++;
            }
            count=1;
            zeme=$6;
        }
    } 
    END{
        if (delka_grafu == -1) {
            if (zeme != "") {print ""zeme": "count"";}
            if (none > 0) {print "None: "none"";}
        } else if (delka_grafu == 0) {
            if (zeme != "") {
                histogram=sprintf("%"int(count/1000)"s","");
                gsub(" ","#",histogram); 
                print zeme ": " histogram;
            }
            if (none > 0) {
                histogram=sprintf("%"int(none/1000)"s","");
                gsub(" ","#",histogram); 
                print "None: " histogram;
            }
        } else {
            zem_arr[pos]=zeme;
            count_arr[pos]=count;
            tmp=count_arr[0];
            for (i=0; i <= pos; i++) {
                if (tmp < count_arr[i]) {
                    tmp=count_arr[i];
                }
            }
            delka_grafu=int(tmp/delka_grafu);
            for (i=0; i < pos; i++) {
                histogram=sprintf("%"int(count_arr[i]/delka_grafu)"s","");  
                gsub(" ","#",histogram); 
                print zem_arr[i]": "histogram;
            }
            if (zeme_arr[pos] != "") {
                histogram=sprintf("%"int(count_arr[pos]/delka_grafu)"s","");  
                gsub(" ","#",histogram); 
                print zem_arr[pos]": "histogram;
            }
            if (none > 0) {
                histogram=sprintf("%"int(none/delka_grafu)"s","");  
                gsub(" ","#",histogram); 
                print "None: " histogram;
            }
        }
    }'
}
####################################################################
#if [ "$#" -eq 0 ]; then
#   hlavicka 
#   cat ${soubor}
#   exit
#fi


pohlavi=""
pred_datum=""
po_datum=""
cmd=""
soubor=""
delka_grafu=-1

## Main ##
while [ $# -ne 0 ]; do
   case $1 in
        -h) print_help; exit;;
        -a) po_datum=$2;shift;;
        -b) pred_datum=$2;shift;;
        -g) pohlavi=$2;shift;
            if [[ pohlavi != "M" || pohlavi != "Z" ]]; then
                echo "U přepínače -g je $pohlavi což není validní" 1>&2
                exit
            fi
            ;;
        -s) if  [[ $2 =~ ^[0-9]+$ ]]; then
                delka_grafu=$2;
                shift;        #!tady bude problém 
            else
                delka_grafu=0;
            fi
            ;;
        -d) echo '-d nebyl implementován';;
        -r) echo '-r nebyl implementován';;
        age | countries | daily | districts | gender | infected | merge | monthly | regions | yearly )
             if [ -z $cmd ]; then
                cmd=$1
            else
                #*error
                echo 'COMMAND může být jen jeden' 1>&2
                exit
            fi ;;
        *.gz) zcat "$1" ;; #add check comand 
        *.bz2) bzcat "$1";; #add check comand
        *.csv) soubor+=" $1";; #E250FF více souborů jenom u marge

   esac
shift
done

if [ -z soubor ]; then
    soubor="/dev/stdin"
fi

valid_datum "$po_datum";
if [ $? == 1 ]; then
    echo "Datum u přepínače -a "$po_datum" není validní" 1>&2
    exit
fi

valid_datum "$pred_datum";
if [ $? == 1 ]; then
    echo "Datum u přepínače -b "$pred_datum" není validní" 1>&2
    exit
fi



case "${cmd}" in
    age) vek;;

    countries) zeme_nakazy;;

    daily) cat ${soubor}| sed 1d | filtry | sort -t, -k2 | awk -F, '{
        if (NR == 1) {
            datum=$2;
            count=0;
        } 
    } 
    {
        if (datum == $2) {
            count++;
        }
        else {
            print ""datum": "count"";
            count=1;
            datum=$2;
        }
    } 
    END{
        if (datum != "") {
            print ""datum": "count"";
        } else if (count > 0) {
            print "None: "count;
        }
    }'
        
    ;;
    districts) kraje_nakazy;;

    gender) cat ${soubor}| sed 1d | filtry | awk -F, "-vdelka_grafu=$delka_grafu" 'BEGIN{
        M=0;
        Z=0;
        count=0;
        none=0
    } {
        if ($4=="M") M++;
        if ($4=="Z") Z++;
        count++;
    } 
    END{
        none=(count - M - Z ); 
        if (delka_grafu == -1) {
            print "M: "M"\nZ: "Z"";
            if (none > 0) print "None: "none""; 
        } else {
            if (delka_grafu == 0) {delka_grafu=100000;}
            else {
                if ((M >= Z) && (M >= none )) {
                    tmp=M;
                } else if ((Z >= M) && (Z >= none )) {
                    tmp=Z;
                } else {
                    tmp=none;
                }
                delka_grafu=int(tmp/delka_grafu);
            }
            histogram=sprintf("%"int(M/delka_grafu)"s","");  
            gsub(" ","#",histogram); 
            print "M: " histogram;
            histogram=sprintf("%"int(Z/delka_grafu)"s","");  
            gsub(" ","#",histogram); 
            print "Z: " histogram;
            if (none > 0) {
                histogram=sprintf("%"int(none/delka_grafu)"s","");  
                gsub(" ","#",histogram); 
                print "None: " histogram;
            }
        }
    }'
    ;;
    infected)
        cat ${soubor}| sed 1d | filtry | awk -F, 'BEGIN{radek=0} {if ($0 > 0) radek++} END{ print radek}'
        #pocet_radku=0;
        #cat ${soubor}| sed 1d | filtry | awk -F, "-vradek=$pocet_radku" '{if ($0 > 0) radek++} END{"$pocet_radku" <= radek}'
        #echo $pocet_radku
    ;;
    merge) #TODO dodělat #00ff00

    ;;
    monthly) cat ${soubor}| sed 1d | filtry | sort -t, -k2 | awk -F, '{
        if (NR == 1) {
            datum=substr($2,1,7);
            count=0;
        } 
    } 
    {
        if (datum == substr($2,1,7)) {
            count++;
        }
        else {
            print ""datum": "count"";
            count=1;
            datum=substr($2,1,7);
        }
    } 
    END{
        if (datum != "") {
            print ""datum": "count"";
        } else if (count > 0) {
            print "None: "count;
        }
    }'

    ;;
    regions) cat ${soubor}| sed 1d | filtry | sort -t, -k5 | awk -F, 'BEGIN {
        zeme="";
        count=1;
        none=0;
    }
    {
        if ($5 == "") {
            none++;
        } 
    } 
    {
        if (zeme == "") {
            zeme=$5;
            next;
        }
        if (zeme == $5) {
            count++;
        }
        else {
            if (zeme != "CZ") {print ""zeme": "count"";}
            count=1;
            zeme=$5;
        }
    } 
    END{
        if (zeme != "") {print ""zeme": "count"";}
        if (none > 0) {print "None: "none"";}
    }'

    ;;
    yearly) cat ${soubor}| sed 1d | filtry | sort -t, -k2 | awk -F, '{
        if (NR == 1) {
            datum=substr($2,1,4);
            count=0;
        } 
    } 
    {
        if (datum == substr($2,1,4)) {
            count++;
        }
        else {
            print ""datum": "count"";
            count=1;
            datum=substr($2,1,4);
        }
    } 
    END{
        if (datum != "") {
            print ""datum": "count"";
        } else if (count > 0) {
            print "None: "count;
        }
    }'

    ;;
    *) hlavicka;
    cat ${soubor}| sed 1d | filtry 
    ;;
esac

#echo "-s je :"$delka_grafu""
# G="Z"; cat osoby-short.csv | awk -F, "-vG=$G" '$4 == G {print $0}'
# awk -F, 'BEGIN{pocet=0} {if ($0 > 0) {pocet++}} END{print pocet}'



#echo $pohlavi $pred_datum $po_datum $cmd;

#awk -F ',' '{ if($3 == $'"$pohlavi"') print $0;}' osoby-short.csv



#awk 'BEGIN{RS=ORS="\r\n"} $4==$pohlavi {print $1 $2 $3 $4 $5}' osoby-short.csv

#cat osoby-short.csv | awk '$='

